### ISSUE TITLE
[Hiba] IndexError: list index out of range

### ISSUE THREAD

**Issue by pcmester** [boapps/ParlaMent-CLI#1]
Szia BoA,
A videó lekérésekor az alábbi hiba jelentkezik: 
```
ciklus          név       kezdet         vége         miniszterelnök       kezdet         vége
    41        2018-  2018.05.08.                        Orbán Viktor  2018.05.10.             
    40    2014-2018  2014.05.06.  2018.05.07.           Orbán Viktor  2014.05.10.  2018.05.10.
    39    2010-2014  2010.05.14.  2014.05.05.           Orbán Viktor  2010.05.29.  2014.05.10.
    38    2006-2010  2006.05.16.  2010.05.13.       Gyurcsány Ferenc  2006.06.09.  2009.04.14.
                                                       Bajnai Gordon  2009.04.14.  2010.05.29.
    37    2002-2006  2002.05.15.  2006.05.15.    Dr. Medgyessy Péter  2002.05.27.  2004.09.29.
                                                    Gyurcsány Ferenc  2004.09.30.  2006.06.08.
    36    1998-2002  1998.06.18.  2002.05.14.           Orbán Viktor  1998.07.06.  2002.05.26.
    35      1994-98  1994.06.28.  1998.06.17.             Horn Gyula  1994.07.15.  1998.07.05.
    34      1990-94  1990.05.02.  1994.06.27.      Dr. Antall József  1990.05.23.  1993.12.12.
                                                    Dr. Boross Péter  1993.12.21.  1994.07.14.
Szavazások mutatása adott ciklusban, két időpont között
kezdet [2020.05.21]: 
vége [2020.05.28]: 
ciklus          név       kezdet         vége         miniszterelnök       kezdet         vége
    41        2018-  2018.05.08.                        Orbán Viktor  2018.05.10.             
    40    2014-2018  2014.05.06.  2018.05.07.           Orbán Viktor  2014.05.10.  2018.05.10.
    39    2010-2014  2010.05.14.  2014.05.05.           Orbán Viktor  2010.05.29.  2014.05.10.
    38    2006-2010  2006.05.16.  2010.05.13.       Gyurcsány Ferenc  2006.06.09.  2009.04.14.
                                                       Bajnai Gordon  2009.04.14.  2010.05.29.
    37    2002-2006  2002.05.15.  2006.05.15.    Dr. Medgyessy Péter  2002.05.27.  2004.09.29.
                                                    Gyurcsány Ferenc  2004.09.30.  2006.06.08.
    36    1998-2002  1998.06.18.  2002.05.14.           Orbán Viktor  1998.07.06.  2002.05.26.
    35      1994-98  1994.06.28.  1998.06.17.             Horn Gyula  1994.07.15.  1998.07.05.
    34      1990-94  1990.05.02.  1994.06.27.      Dr. Antall József  1990.05.23.  1993.12.12.
                                                    Dr. Boross Péter  1993.12.21.  1994.07.14.
válassz ciklust: 40
válassz ülésnapot: 1
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sgis.parlament.hu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sgis.parlament.hu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
lehetséges felbontások: 448x252, 640x360, 896x504, 1280x720
felbontás [1280x720]: 
Traceback (most recent call last):
  File "parlament_video.py", line 95, in <module>
    duration = getDuration(f4m_url)
  File "parlament_video.py", line 55, in getDuration
    return re.findall(r'<duration>(.*)</duration>', str(f4m_response.content))[0]
IndexError: list index out of range
```
OS: Manjaro Linux
Python verzió: 3.8.2
A szavazások rendesen működnek.

Üdv,
pcmester!

**Comment by boapps** [comment]
Szia, köszi a hibajelentést, dobtam rá egy fixet, elvileg már kéne, hogy működjön.

**Comment by pcmester** [comment]
Köszönöm szépen a gyors javítást! Most az alábbi hiba jelentkezik:
```
Traceback (most recent call last):
  File "parlament_video.py", line 97, in <module>
    selected_duration = float(input('hossz [{}]: '.format(duration)))
ValueError: could not convert string to float: ''
```
Hogyha egész számot írok be neki, akkor egy ideig vár, aztán kilép üzenet nélkül.

Üdv,
pcmester

**Comment by boapps** [comment]
Elvileg létre kéne hozzon egy test.mp4 fájlt (amikor nem dob errort) és igen, ez így elég fapados, még változni fog.

**Comment by pcmester** [comment]
Köszönöm szépen, most jól működik!

Sajnos ismét egy hiba, ha a 38-as ciklust választom (2006-2010), akkor a következő hiba jelentkezik:
```
válassz ciklust: 38
dátum       nap
Traceback (most recent call last):
  File "parlament_video.py", line 86, in <module>
    selected_day = input('válassz ülésnapot [{}]: '.format(days[0][0])).strip()
IndexError: list index out of range
```

**Comment by boapps** [comment]
Na elvileg ez is fixelve, bocsi hogy eddig tartott, elfelejtettem...

**Comment by pcmester** [comment]
Semmi gond, köszönöm szépen a javítást! A float inputos gond továbbra is fennáll sajnos, de ez orvosolható manuális beavatkozással, (egész számok beírásával) ideiglenesen
